# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("strings.proto", :syntax => :proto3) do
    add_message "TestData" do
      optional :field1, :double, 1
      optional :field2, :double, 2
      optional :field3, :double, 3
      optional :field4, :double, 4
      optional :field5, :double, 5
      optional :field6, :double, 6
      optional :field7, :double, 7
      optional :field8, :double, 8
      optional :field9, :double, 9
      optional :field10, :double, 10
    end
  end
end

TestData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestData").msgclass
