# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("strings.proto", :syntax => :proto3) do
    add_message "TestData" do
      optional :field1, :string, 1
      optional :field2, :string, 2
      optional :field3, :string, 3
      optional :field4, :string, 4
      optional :field5, :string, 5
      optional :field6, :string, 6
      optional :field7, :string, 7
      optional :field8, :string, 8
      optional :field9, :string, 9
      optional :field10, :string, 10
    end
  end
end

TestData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestData").msgclass
