# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integers.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("integers.proto", :syntax => :proto3) do
    add_message "TestData" do
      optional :field1, :int64, 1
      optional :field2, :int64, 2
      optional :field3, :int64, 3
      optional :field4, :int64, 4
      optional :field5, :int64, 5
      optional :field6, :int64, 6
      optional :field7, :int64, 7
      optional :field8, :int64, 8
      optional :field9, :int64, 9
      optional :field10, :int64, 10
    end
  end
end

TestData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestData").msgclass
